### ISSUE TITLE
SNS

### ISSUE THREAD

**Issue by pattyrlin** [nicel1/wany#1]
Use SNS to monitor number of users on system

**Comment by pattyrlin** [comment]
I have sns subscriptions working for SMS texts. Will push to git when I have a chance

**Comment by GreggFalcon11** [comment]
I looked at your code and saw that it just adds the users to a topic. From what I remember it looked like publish would only push to an entire topic. If we want to implement text address, we would have to create a topic for each user i think then put them in that one. I may be wrong but i think that is the only way. It is not very well thought out, but it could work well enough for this classes purposes just do that. I dont know if billing works on a per topic basis though so you may want look into that otherwise we could just sns a newsletter like thing. not really sure.

**Comment by pattyrlin** [comment]
Hey,
Yeah you're right. I'm working on Changing that now actually. Thanks for
the heads up~
